### ISSUE TITLE
build official docker image for each new release

### ISSUE THREAD

**Issue by niepi** [nightscout/cgm-remote-monitor#5503]
**Is your feature request related to a problem? Please describe.**
I run NS in docker/kubernetes and build the image myself when a new version is released.

**Describe the solution you'd like**
Provide an official NS docker image on Docker Hub. This could be achieved with the following steps:

- provide a dockerfile for the official image
- integrate docker hub to build this image automatically when a new tag is push to the repo

**Comment by DOFfactory** [comment]
I fully support this, I would love to run NS on my own server accessible via VPN. I am somewhat hesitant running it on cloud.

**Comment by niepi** [comment]
Is there anything I can do? 

The repo has a Dockerfile.example that basically works, but most of the work is the configuration on the docker hub side.

**Comment by DOFfactory** [comment]
Well, as far as I can see one has to `git clone` instead of downloading a ready made docker container everything with 1 command, and a `docker-compose` would be lovely (and much simpler than cloning and building and debugging for build errors)

**Comment by niepi** [comment]
this is my current docker-compose setup:

```
version: "2"
networks:
    nginx-proxy:
    nightscout:
services:
  nginx-proxy:
  ...
  letsencrypt:
  ...
  database:
    restart: unless-stopped
    image: 'mongo:latest'
    environment:
      AUTH: 'true'
    volumes:
      - ./data/mongo:/data/db:cached
      - ./import:/import
    ports:
      - '27017'
    networks:
      - nightscout

  nightscout:
    restart: unless-stopped
    image: 'niepi/cgm-remote-monitor:13.0.1'
    environment:
      VIRTUAL_HOST: ns.example.com
      VIRTUAL_PORT: 1337
      LETSENCRYPT_HOST: ns.example.com
      LETSENCRYPT_EMAIL: example@example.com
      API_SECRET: 'secret'
      AUTH_DEFAULT_ROLES: 'denied'
      MONGO_CONNECTION: 'mongodb://nightscout:secret@database/nightscout'
      PORT: 1337
      MONGO_COLLECTION: 'entries'
      NIGHT_MODE: 'off'
      SHOW_RAWBG: 'never'
      THEME: 'default'
      TIME_FORMAT: '24'
      DISPLAY_UNITS: 'mg/dl'
      ... # more NS env vars
    networks:
      - nightscout
      - nginx-proxy
    ports:
      - '1337'
```
