### ISSUE TITLE
Sensor values not showing on main page (docker self hosted Nightscout / MongoDB)

### ISSUE THREAD

**Issue by mwinterstorm** [nightscout/cgm-remote-monitor#7590]
**Describe the bug**
Set up selfhosted Nightscout and MongoDB in docker on local machine. Using xdrip as uploader. xdrip is uploading and Nightscout is receiving data and writing to MongoDB, confirmed using API which shows sensor data and sgv is showing in Nightscout reports. Treatments and device status show up, but sensor glucose not showing on main page. Sensor glucose is showing in reports.

Might be a duplicate of https://github.com/nightscout/cgm-remote-monitor/issues/7479 - apologies if I should have commented there instead.

**To Reproduce**
1. Nightscout just doesn't show sensor values

**Expected behavior**
Sensor values / graph should be shown on on main page, but don't show.

**Screenshots**
Main page - missing sensor values, but showing treatment: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28850511/194016734-46509dd8-9441-40cf-a581-3d3e4897b6fe.png">

Reports - showing sensor values and treatment:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28850511/194016900-24e5bb74-bdb7-4bde-85a7-367b65aeb219.png">

**Your setup information**
- Version: Nightscout 14.2.6 deployed on local docker (see compose below)
- Dexcom G6 with uploader xdrip+ on an Pixel 3A
- Confirmed sgv values not showing on Firefox or Safari on MacOS or Firefox or Chrome on Android
- Confirmed not showing if site accessed via IP address on local network or via nginx reverse proxy

**Additional context**
Docker compose used:
```
version: '3.4'
services:
  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    environment:
      TZ: Pacific/Auckland
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout
      API_SECRET: **************************
      BG_HIGH: 15
      BG_LOW: 3
      BG_TARGET_TOP: 10
      BG_TARGET_BOTTOM: 4
      INSECURE_USE_HTTP: "true"
      AUTH_DEFAULT_ROLES: readable devicestatus-upload
      ENABLE: careportal rawbg boluscalc food iob cob bwp cage sage basal bolus googlehome dbsize
      DISPLAY_UNITS: mmol
      BASE_URL: *****.*****.com
    ports:
      - "1337:1337"
    depends_on:
      - mongo
    volumes:
      - /home/docker/nightscout:/var/opt/ssl/:ro
    restart: always
  mongo:
    image: mongo:4.4.9
    volumes:
      - ./nightscout/data:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
      - "28017:28017"
    restart: always
```
